version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  spring-boot-app:
    container_name: spring-boot-app
    build: .
    image: spring-mysql-gymmanager.jar
    restart: always
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: practice
      MYSQL_USER: root
      MYSQL_PASSWORD: root

